# Generated by Django 4.2.3 on 2023-08-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_products_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
    ]
