# Generated by Django 4.2.3 on 2023-08-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_cod',
            new_name='payment_mode',
        ),
    ]
